services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pg_tm
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pg1_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"

  redis:
    image: redis:8-alpine
    container_name: auth_redis_tm
    expose:
      - "6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rb_tm
    hostname: rabbitmq
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongo:
    image: mongo:8.2.2
    container_name: mongo_tm
    hostname: mongo
    restart: unless-stopped
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  eureka-server:
    build: ./backend/eureka-server
    container_name: eureka-server
    expose:
      - "8761"

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    expose:
      - "8000"
    environment:
      - JWT_PRIVATE_KEY_PATH=file:/app/certs/private_key.pem
      - JWT_PUBLIC_KEY_PATH=file:/app/certs/public_key.pem
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_TTL=${JWT_TTL}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - COOKIE_SAME_SITE=${COOKIE_SAME_SITE}
      - DB_URL=jdbc:postgresql://postgres:5432/user_db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - INTERNAL_SECRET_KEY=${INTERNAL_SECRET_KEY}
      - EUREKA_URI=${EUREKA_URI}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
    depends_on:
      - postgres
      - redis
      - eureka-server
      - rabbitmq
    volumes:
      - ./certs:/app/certs

  core-service:
    build: ./backend/core-service
    container_name: core-service
    expose:
      - "8001"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/core_db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - INTERNAL_SECRET_KEY=${INTERNAL_SECRET_KEY}
      - EUREKA_URI=${EUREKA_URI}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - CORS_ALLOWED_ORIGINS=${FRONTEND_URL}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - postgres
      - redis
      - eureka-server
      - rabbitmq

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "1004:1004"
    environment:
      - EUREKA_URI=${EUREKA_URI}
      - REDIS_HOST=redis
      - JWT_PUBLIC_KEY_PATH=file:/app/certs/public_key.pem
      - CORS_ALLOWED_ORIGINS=${FRONTEND_URL}
    depends_on:
      - eureka-server
      - redis
    volumes:
      - ./certs:/app/certs

  activity-service:
    build: ./backend/activity-service
    container_name: activity-service
    expose:
      - "8002"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/activity_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
      - EUREKA_URI=${EUREKA_URI}
    depends_on:
      - eureka-server
      - mongo
      - rabbitmq


  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    expose:
      - "8003"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/notification_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
      - MAIL_SENDER_USERNAME=${MAIL_SENDER_USERNAME}
      - MAIL_SENDER_PASSWORD=${MAIL_SENDER_PASSWORD}
      - MAIL_HOST=smtp-relay.brevo.com
      - MAIL_PORT=587
      - MAIL_SENDER=${FROM_MAIL}
      - MAIL_NAME=${FROM_NAME}
      - EUREKA_URI=${EUREKA_URI}
    depends_on:
      - eureka-server
      - rabbitmq
      - mongo

  ai-service:
    build: ./backend/ai-service
    container_name: ai-service
    expose:
      - "8004"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/ai_db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
      - API_KEY=${OPENROUTER_API_KEY}
      - BASE_URL=${OPENROUTER_BASE_URL}
      - MODEL=${OPENROUTER_MODEL}
      - EUREKA_URI=${EUREKA_URI}
      - INTERNAL_SECRET_KEY=${INTERNAL_SECRET_KEY}
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - eureka-server
      - rabbitmq
      - postgres

  frontend-web:
    build: frontend/app
    container_name: tm_frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway



volumes:
  pg1_data:
  redis_data:
  mongo_data:
  mongo_config:
  rabbitmq_data:

