services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pg_tm
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:8-alpine
    container_name: auth_redis_tm
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rb_tm
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongo:
    image: mongo:8.2.2
    container_name: mongo_tm
    hostname: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  eureka-server:
    build: ./backend/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      - JWT_PRIVATE_KEY_PATH=file:/app/certs/private_key.pem
      - JWT_PUBLIC_KEY_PATH=file:/app/certs/public_key.pem
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_TTL=${JWT_TTL}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - COOKIE_SAME_SITE=${COOKIE_SAME_SITE}
      - DB_URL=jdbc:postgresql://postgres:5432/user_db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - INTERNAL_SECRET_KEY=${INTERNAL_SECRET_KEY}
      - EUREKA_URI=${EUREKA_URI}
    depends_on:
      - postgres
      - redis
      - eureka-server
    volumes:
      - ./certs:/app/certs

  core-service:
    build: ./backend/core-service
    container_name: core-service
    ports:
      - "8001:8001"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/core_db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - INTERNAL_SECRET_KEY=${INTERNAL_SECRET_KEY}
      - EUREKA_URI=${EUREKA_URI}
      - JWT_PUBLIC_KEY_PATH=file:/app/certs/public_key.pem
      - SPRING_RABBITMQ_HOST=rabbitmq
      - CORS_ALLOWED_ORIGINS=${FRONTEND_URL}
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - postgres
      - redis
      - eureka-server
      - rabbitmq
    volumes:
      - ./certs:/app/certs

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "1004:1004"
    environment:
      - EUREKA_URI=${EUREKA_URI}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - eureka-server
      - auth-service
      - core-service
      - activity-service

  activity-service:
    build: ./backend/activity-service
    container_name: activity-service
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/activity_db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_URI=${EUREKA_URI}
      - REDIS_HOST=redis
      - JWT_PUBLIC_KEY_PATH=file:/app/certs/public_key.pem
    depends_on:
      - eureka-server
      - mongo
      - rabbitmq
      - redis
    volumes:
      - ./certs:/app/certs

  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    ports:
      - "8003:8003"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - MAIL_SENDER_USERNAME=${MAIL_SENDER_USERNAME}
      - MAIL_SENDER_PASSWORD=${MAIL_SENDER_PASSWORD}
      - FROM_MAIL=${FROM_MAIL}
      - EUREKA_URI=${EUREKA_URI}
    depends_on:
      - eureka-server
      - rabbitmq

volumes:
  pg_data:
  redis_data:
  mongo_data:
  mongo_config:
  rabbitmq_data:

