spring:
  application:
    name: ai-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ai_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: ${BASE_URL}
      chat:
        options:
          model: ${MODEL}
          temperature: 0.2
    vectorstore:
      pgvector:
        dimensions: 384
        initialize-schema: true
    embedding:
      transformer:
        cache:
          enabled: true
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:schema.sql

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3
          multiplier: 2


internal:
  secret-key: ${INTERNAL_SECRET_KEY}
server:
  port: 8004

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

logging.level.org.springframework.ai: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always